

SELECT 
COUNT(*),
min(SERVICE_FROM_DATE),
max(service_from_date),
sum(AMOUNT_TOTAL_PAID)
FROM 
OA_CSIN.MST_MEDICAL_CLAIMS



SELECT 
AXIAL_PLACE_OF_SERVICE_NAME ,
sum(AMOUNT_ALLOWED),
sum(AMOUNT_TOTAL_PAID),
COUNT(*)
FROM 
OA_CSIN.MST_MEDICAL_CLAIMS
GROUP BY 1
ORDER BY 1


SELECT 
AXIAL_PLACE_OF_SERVICE_NAME ,
sum(AMOUNT_ALLOWED),
sum(AMOUNT_TOTAL_PAID),
COUNT(*)
FROM 
OA_CSIN.MST_MEDICAL_CLAIMS
GROUP BY 1
ORDER BY 1

SELECT 
b.PLAN_NAME ,
sum(AMOUNT_ALLOWED),
sum(AMOUNT_TOTAL_PAID),
COUNT(*)
FROM 
OA_CSIN.MST_MEDICAL_CLAIMS  a
INNER JOIN
OA_CSIN.MST_MEMBER_MONTH_BY_LOB  b  
ON 
a.AXIAL_MEMBER_ID = b.AXIAL_MEMBER_ID  AND 
a.SERVICE_FROM_YYYY_MM  = b.REPORTING_YYYY_MM 
GROUP BY 1
ORDER BY 1
-----------------------------------------------------------------------------------------------------------------------



SELECT 
COUNT(*) ,
min(SERVICE_FROM_DATE),
max(service_from_date),
sum(AMOUNT_TOTAL_PAID)
FROM 
OA_CSIN.MST_rx_CLAIMS



SELECT 
SERVICE_FROM_MONTH ,
sum(AMOUNT_ALLOWED),
sum(AMOUNT_TOTAL_PAID),
COUNT(*)
FROM 
OA_CSIN.MST_rx_CLAIMS
GROUP BY 1
ORDER BY 1




SELECT 
b.PLAN_NAME ,
sum(AMOUNT_ALLOWED),
sum(AMOUNT_TOTAL_PAID),
COUNT(*)
FROM 
OA_CSIN.MST_rx_CLAIMS a
INNER JOIN
OA_CSIN.MST_MEMBER_MONTH_BY_LOB  b  
ON 
a.AXIAL_MEMBER_ID = b.AXIAL_MEMBER_ID  AND 
a.SERVICE_FROM_YYYY_MM  = b.REPORTING_YYYY_MM 
GROUP BY 1
ORDER BY 1



SELECT count(*) FROM 
OA_CSIN.MST_PROVIDER_DIM








SELECT PROVIDER_TYPE ,count(*) FROM 
OA_CSIN.MST_PROVIDER_DIM
GROUP BY 1 
ORDER BY 1 



SELECT PROVIDER_GROUP_NAME ,count(*) FROM 
OA_CSIN.MST_PROVIDER_DIM
GROUP BY 1 
ORDER BY 1 


SELECT member_gender,count(*) FROM 

(
SELECT
AXIAL_MEMBER_ID ,
MEMBER_DATE_OF_BIRTH ,
MEMBER_ZIP ,
MEMBER_RACE ,
MEMBER_GENDER
FROM
OA_CSIN.MST_MEMBER_DIM
WHERE client_id = 81
)
GROUP BY 1




SELECT PLAN_NAME ,count(DISTINCT AXIAL_MEMBER_ID) FROM 
OA_CSIN.MST_MEMBER_MONTH_BY_LOB
GROUP BY 1
ORDER BY 1



SELECT count(*) FROM 
OA_CSIN.MST_MEMBER_MONTH_BY_LOB
GROUP BY 1
ORDER BY 1



SELECT PLACE_OF_SERVICE , count(*) FROM 
OA_CSIN.MEDICAL_CLAIM_DX_LONG
GROUP BY 1
ORDER BY 1


SELECT count(*) FROM 
OA_CSIN.MEDICAL_CLAIM_DX_LONG




SELECT *  FROM 
CARE_MANAGEMENT.CRS_ACTION_PLAN
WHERE ACTION_PLAN_TEMPLATE_NAME  IS NOT NULL 



SELECT * FROM 
REFERENCE.ICD_DIAGNOSIS
 WHERE  
    IS_OPIOID_OVERDOSE=TRUE
       and is_drug_overdose_of_interest is true 
drug_overdose_type = 'adverse effect'
      and is_drug_overdose_of_interest is true 
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    




